<?php

namespace Burxon\LetterExchange;

use Illuminate\Support\Str;

class LetterExchange
{
    public function test(): string
    {
        return "тест";
    }

    protected function cyrillic_to_lower($cyrillicString)
    {
        $cyr = [
            'А',
            'Б',
            'В',
            'Г',
            'Д',
            'Е',
            'Ё',
            'Ж',
            'З',
            'И',
            'Й',
            'К',
            'Л',
            'М',
            'Н',
            'О',
            'П',
            'Ғ',
            'Ҳ',
            'Қ',
            'Р',
            'С',
            'Т',
            'У',
            'Ф',
            'Х',
            'Ц',
            'Ч',
            'Ш',
            'Ў',
            'Ъ',
            'Ы',
            'Ь',
            'Э',
            'Ю',
            'Я',
        ];
        $lat = [
            'а',
            'б',
            'в',
            'г',
            'д',
            'е',
            'ё',
            'ж',
            'з',
            'и',
            'й',
            'к',
            'л',
            'м',
            'н',
            'о',
            'п',
            'ғ',
            'ҳ',
            'қ',
            'р',
            'с',
            'т',
            'у',
            'ф',
            'х',
            'ц',
            'ч',
            'ш',
            'ў',
            'ъ',
            'ы',
            'ь',
            'э',
            'ю',
            'я',
        ];

        return str_replace($cyr, $lat, $cyrillicString);
    }

    protected function cyrillic_to_upper($cyrillicString)
    {
        $cyr = [

            'А',
            'Б',
            'В',
            'Г',
            'Д',
            'Е',
            'Ё',
            'Ж',
            'З',
            'И',
            'Й',
            'К',
            'Л',
            'М',
            'Н',
            'О',
            'П',
            'Ғ',
            'Ҳ',
            'Қ',
            'Р',
            'С',
            'Т',
            'У',
            'Ф',
            'Х',
            'Ц',
            'Ч',
            'Ш',
            'Ў',
            'Ъ',
            'Ы',
            'Ь',
            'Э',
            'Ю',
            'Я',
        ];
        $lat = [
            'а',
            'б',
            'в',
            'г',
            'д',
            'е',
            'ё',
            'ж',
            'з',
            'и',
            'й',
            'к',
            'л',
            'м',
            'н',
            'о',
            'п',
            'ғ',
            'ҳ',
            'қ',
            'р',
            'с',
            'т',
            'у',
            'ф',
            'х',
            'ц',
            'ч',
            'ш',
            'ў',
            'ъ',
            'ы',
            'ь',
            'э',
            'ю',
            'я',
        ];

        return str_replace($lat, $cyr, $cyrillicString);
    }

    public function isCyrillic($text)
    {
        return preg_match('/[А-Яа-яЁё]/u', $text);
    }

    public function cyrillic_to_latin($cyrillicString)
    {
        $cyr = [
            'а',
            'б',
            'в',
            'г',
            'д',
            'е',
            'ё',
            'ж',
            'з',
            'и',
            'й',
            'к',
            'л',
            'м',
            'н',
            'о',
            'п',
            'ғ',
            'ҳ',
            'Ғ',
            'Ҳ',
            'қ',
            'Қ',
            'р',
            'с',
            'т',
            'у',
            'ф',
            'х',
            'ц',
            'ч',
            'ш',
            'ў',
            'ъ',
            'ы',
            'ь',
            'э',
            'ю',
            'я',
            'А',
            'Б',
            'В',
            'Г',
            'Д',
            'Е',
            'Ё',
            'Ж',
            'З',
            'И',
            'Й',
            'К',
            'Л',
            'М',
            'Н',
            'О',
            'П',
            'Р',
            'С',
            'Т',
            'У',
            'Ф',
            'Х',
            'Ц',
            'Ч',
            'Ш',
            'Ў',
            'Ъ',
            'Ы',
            'Ь',
            'Э',
            'Ю',
            'Я',
        ];
        $lat = [
            'a',
            'b',
            'v',
            'g',
            'd',
            'e',
            'yo',
            'j',
            'z',
            'i',
            'y',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'g\'',
            'h',
            'G\'',
            'H',
            'q',
            'Q',
            'r',
            's',
            't',
            'u',
            'f',
            'x',
            's',
            'ch',
            'sh',
            'o\'',
            '',
            '',
            '',
            'e',
            'yu',
            'ya',
            'A',
            'B',
            'V',
            'G',
            'D',
            'E',
            'Yo',
            'J',
            'Z',
            'I',
            'Y',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'R',
            'S',
            'T',
            'U',
            'F',
            'X',
            'S',
            'Ch',
            'Sh',
            'O\'',
            '',
            '',
            '',
            'E',
            'Yu',
            'Ya',
        ];

        return str_replace($cyr, $lat, $cyrillicString);
    }

    public function latin_to_cyrillic($cyrillicString)
    {
        $cyr = [
            'а',
            'б',
            'в',
            'г',
            'д',
            'е',
            'ё',
            'ж',
            'з',
            'и',
            'й',
            'к',
            'л',
            'м',
            'н',
            'о',
            'п',
            'ғ',
            'ҳ',
            'Ғ',
            'Ҳ',
            'қ',
            'Қ',
            'р',
            'ш',
            'с',
            'т',
            'у',
            'ф',
            'х',
            'ц',
            'ч',
            'ў',
            'ъ',
            'ы',
            'ь',
            'э',
            'ю',
            'я',
            'А',
            'Б',
            'В',
            'Г',
            'Д',
            'Е',
            'Ё',
            'Ж',
            'З',
            'И',
            'Й',
            'К',
            'Л',
            'М',
            'Н',
            'О',
            'П',
            'Р',
            'С',
            'Т',
            'У',
            'Ф',
            'Х',
            'Ц',
            'Ч',
            'Ш',
            'Ў',
            'Ъ',
            'Ы',
            'Ь',
            'Э',
            'Ю',
            'Я',
        ];
        $lat = [
            'a',
            'b',
            'v',
            'g',
            'd',
            'e',
            'yo',
            'j',
            'z',
            'i',
            'y',
            'k',
            'l',
            'm',
            'n',
            'o',
            'p',
            'g\'',
            'h',
            'G\'',
            'H',
            'q',
            'Q',
            'r',
            'sh',
            's',
            't',
            'u',
            'f',
            'x',
            's',
            'ch',
            'o\'',
            '',
            '',
            '',
            'e',
            'yu',
            'ya',
            'A',
            'B',
            'V',
            'G',
            'D',
            'E',
            'Yo',
            'J',
            'Z',
            'I',
            'Y',
            'K',
            'L',
            'M',
            'N',
            'O',
            'P',
            'R',
            'S',
            'T',
            'U',
            'F',
            'X',
            'S',
            'Ch',
            'Sh',
            'O\'',
            '',
            '',
            '',
            'E',
            'Yu',
            'Ya',
        ];

        return str_replace($lat, $cyr, $cyrillicString);
    }

    public function toUCFirst($text)
    {
        $names = explode(' ', $text);
        $lower = '';
        foreach ($names as $name) {
            $lower .= mb_substr($name, 0, 1, 'UTF-8') . $this->cyrillic_to_lower(mb_substr($name, 1, mb_strlen($name, 'UTF-8'), 'UTF-8')) . ' ';
        }

        return trim($lower);
    }

    public function toLatin($text)
    {
        $text = $this->cyrillic_to_latin($text);

        return Str::lower($text);
    }

    public function toCyrillic($text)
    {
        $text = Str::lower($text);
        $text = str_replace('sh', 'ш', $text);
        $text = str_replace('ch', 'ч', $text);
        $text = str_replace("o'", 'ў', $text);
        $text = str_replace("g'", 'ғ', $text);
        $text = str_replace('yu', 'ю', $text);
        $text = str_replace('ya', 'я', $text);
        $text = str_replace('yo', 'ё', $text);
        $text = $this->latin_to_cyrillic($text);

        return Str::lower($text);
    }
}
